### ISSUE TITLE
Null error - might be language related

### ISSUE THREAD

**Issue by NISPico** [ZioTino/Our.Umbraco.Skipper#6]
In the umbraco log i sometimes get this null error, could you maybe add a null check here?

I have a feeling its because on my site, i have 2 languages set up, but only a hostname for the Danish one. 

```
System.ArgumentNullException: Value cannot be null. (Parameter 'Base GetUrl for Id 4549.')
   at Our.Umbraco.Skipper.SkipperUrlProvider.BuildUrl(IPublishedContent content, Uri current, UrlMode mode, String culture)
   at Our.Umbraco.Skipper.SkipperUrlProvider.GetUrl(IPublishedContent content, UrlMode mode, String culture, Uri current)
   at Umbraco.Cms.Core.Routing.UrlProvider.<>c__DisplayClass14_0.<GetUrl>b__1(IUrlProvider provider)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Umbraco.Cms.Core.Routing.UrlProvider.GetUrl(IPublishedContent content, UrlMode mode, String culture, Uri current)
   at Umbraco.Cms.Core.Routing.UrlProvider.GetUrl(Int32 id, UrlMode mode, String culture, Uri current)
   at Umbraco.Extensions.UrlProviderExtensions.GetContentUrlsByCultureAsync(IContent content, IEnumerable`1 cultures, IPublishedRouter publishedRouter, IUmbracoContext umbracoContext, IContentService contentService, ILocalizedTextService textService, IVariationContextAccessor variationContextAccessor, ILogger logger, UriUtility uriUtility, IPublishedUrlProvider publishedUrlProvider)
```

**Comment by archimedecreativa** [comment]
Hi @NISPico 
Can you update and retry?
Thank you!

**Comment by NISPico** [comment]
@archimedecreativa 

I get an error here now, "System.ExecutionEngineException: 'Exception of type 'System.ExecutionEngineException' was thrown.'"

`private static IntPtr LoadLibrary(string library, bool failOnLoadFailure)
        {
            if (!NativeLibrary.TryLoad(library, typeof(object).Assembly, DllImportSearchPath.ApplicationDirectory | DllImportSearchPath.System32, out IntPtr lib) && failOnLoadFailure)
            {
                Environment.FailFast($"Failed to load app-local ICU: {library}");
            }

            return lib;
        }`
        
All i have done is update the package
